spring:
  datasource:
    url: jdbc:mysql://27.96.135.222:3306/likelion
    username: ehdrb01
    password: Rlaehdrb12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  upload:
    dir: /path/to/upload/directory
  mvc:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS






  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true

logging:
  level:
    org.hibernate.sql: debug


